/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ezbake.base.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PurgeStatus implements org.apache.thrift.TEnum {
  UNKNOWN_ID(0),
  WAITING_TO_START(1),
  STARTING(2),
  PURGING(3),
  STOPPING(4),
  ERROR(5),
  FINISHED_COMPLETE(6),
  FINISHED_INCOMPLETE(7);

  private final int value;

  private PurgeStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PurgeStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return UNKNOWN_ID;
      case 1:
        return WAITING_TO_START;
      case 2:
        return STARTING;
      case 3:
        return PURGING;
      case 4:
        return STOPPING;
      case 5:
        return ERROR;
      case 6:
        return FINISHED_COMPLETE;
      case 7:
        return FINISHED_INCOMPLETE;
      default:
        return null;
    }
  }
}
